server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header Cross-Origin-Embedder-Policy "credentialless" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
